= Cheatsheets

[[ErrorLocation]]
== ErrorLocation

++++
 Data object that holds the location of a graphql query error.
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[column]]`column`|`Number (int)`|
+++

+++
|[[line]]`line`|`Number (int)`|
+++

+++
|===

[[QueryError]]
== QueryError

++++
 Data object that represents an error that occurred upon execution of a GraphQL query.
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[errorType]]`errorType`|`String`|
+++
Gets the type of the graphql execution error.
 <p>
 The possible types are determined by the `ValidationErrorType` enum defined in the GraphQL implementation
 (refer to: https://github.com/graphql-java/graphql-java).
+++
|[[locations]]`locations`|`Array of link:dataobjects.html#ErrorLocation[ErrorLocation]`|
+++

+++
|[[message]]`message`|`String`|
+++

+++
|===

[[QueryResult]]
== QueryResult

++++
 Immutable data object that holds the execution result of a GraphQL query.
 <p>
 If the query was successful the response is available as . Otherwise a list of
  provides more detail on the failure.
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[data]]`data`|`Json object`|
+++
Gets the  response of a successful GraphQL query. If the query wasn't
 successful an empty json object is returned.
+++
|[[errors]]`errors`|`Array of link:dataobjects.html#QueryError[QueryError]`|
+++
Gets the errors that occurred on query execution, if the GraphQL query was not successful.
+++
|[[succeeded]]`succeeded`|`Boolean`|
+++

+++
|===

[[SchemaMetadata]]
== SchemaMetadata


[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[async]]`async`|`Boolean`|-
|[[deliveryOptions]]`deliveryOptions`|`link:dataobjects.html#DeliveryOptions[DeliveryOptions]`|-
|[[schemaName]]`schemaName`|`String`|-
|[[serviceAddress]]`serviceAddress`|`String`|-
|===

[[SchemaReferenceData]]
== SchemaReferenceData

++++
 Immutable data object that represents the state of a link when a
 service discovery `usage` event occurs that matches a published schema.
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[discoveryName]]`discoveryName`|`String`|
+++

+++
|[[record]]`record`|`link:dataobjects.html#Record[Record]`|
+++
Gets the service record of the service that is referenced.
+++
|[[status]]`status`|`link:enums.html#Status[Status]`|
+++
Gets the status of the link which can be either
  or
+++
|===

